In [7]:
from sqlalchemy import and_
from sqlalchemy.orm import Query

from qdatasdk import Security, run_query, EquFreeShares, EquShareChange


# 查询自由流通股本
fields = [EquFreeShares.ID, EquFreeShares.PARTY_ID,
          EquFreeShares.PUBLISH_DATE, EquFreeShares.CHANGE_DATE,
          EquFreeShares.TICKER_SYMBOL,
          EquFreeShares.FREE_SHARES]
q = Query(fields).filter(and_(EquFreeShares.PARTY_ID == Security.PARTY_ID,
                              Security.TICKER_SYMBOL == "000001",
                              EquFreeShares.PUBLISH_DATE >= "1900-01-01")).order_by(
    EquFreeShares.PUBLISH_DATE.desc()).limit(5)

df = run_query(q)
df

       ID  PARTY_ID PUBLISH_DATE CHANGE_DATE TICKER_SYMBOL      FREE_SHARES
0  124030         2   2022-08-18  2022-06-30        000001  8600906226.0000
1  101666         2   2022-03-10  2021-12-31        000001  8600881226.0000
2   72135         2   2021-02-02  2020-12-31        000001  8601113751.0000
3   44672         2   2019-10-22  2019-09-30        000001  8601111956.0000
4   10422         2   2019-09-27  2019-09-18        000001  9845796830.0000

In [8]:
# 查询总股本
fields = [EquShareChange.ID, EquShareChange.PARTY_ID,
          EquShareChange.PUBLISH_DATE, EquShareChange.CHANGE_DATE,
          EquShareChange.TOTAL_SHARES]
q = Query(fields).filter(and_(EquShareChange.PARTY_ID == Security.PARTY_ID,
                              Security.TICKER_SYMBOL == "000001",
                              EquShareChange.PUBLISH_DATE >= "1900-01-01")).order_by(
    EquShareChange.PUBLISH_DATE.desc()).limit(5)
df = run_query(q)
df

       ID  PARTY_ID PUBLISH_DATE CHANGE_DATE TOTAL_SHARES
0  533475         2   2023-08-24  2023-06-30  19405918200
1  522243         2   2023-03-09  2022-12-31  19405918200
2  513699         2   2022-08-18  2022-06-30  19405918200
3  504061         2   2022-03-10  2021-12-31  19405918200
4  484804         2   2021-08-20  2021-06-30  19405918200